### ISSUE TITLE
Add Hover Links to Headers

### ISSUE THREAD

**Issue by carlsapp** [Wyndham-Forest-HOA/wyndham-forest-hoa.github.io#6]
An effect similar to what GitHub does with headers in markdown files. So people can hover over a header and get easily get a link to share.

**Comment by narain44** [comment]
Something like this ?
![image](https://user-images.githubusercontent.com/36483755/78280209-bb2fe600-74e6-11ea-8afd-9c994bcab1c0.png)

**Comment by carlsapp** [comment]
Yeah, that's what I was thinking. And place the link icon either before or after the text. Whichever looks better. We could also make it so when they click on the link icon, the link is automatically copied to their clipboard.

**Comment by carlsapp** [comment]
Yeah, that's what I was thinking. And place the link icon either before or after the text. Whichever looks better. We could also make it so when they click on the link icon, the link is automatically copied to their clipboard.

**Comment by narain44** [comment]
Updated Restaurants with "Copy links" feature
<img width="462" alt="Screen Shot 2020-04-06 at 7 34 44 AM" src="https://user-images.githubusercontent.com/36483755/78554454-2f190980-77d9-11ea-8041-72b00b22c73b.png">

**Comment by narain44** [comment]
Completed.
